FROM python:3.11.0b4-slim-buster
COPY . .
CMD ["python", "./hello.py"]


# FROM python:3.11.0b4-slim-buster
# WORKDIR /application
# COPY . .
# RUN pip install -r requirements.txt
# EXPOSE 5000
# CMD ["python", "./hello.py"]
